post http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjVkNjdlMWQ0MGJkODg4MjJjYTYwNWNjMCIsImlhdCI6MTU2NzA5ODA0NH0.aGwqJzZom3GL_dgrY0OtzwAjYh8C_3fia_fMF-DUHaA

{
    "title": "blog005",
    "author": "Erick B. Lemos",
    "url": "url",
    "likes": 123,
    "userId": "5d67e1d40bd88822ca605cc0"
}