post http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjVkNjdlMWQ0MGJkODg4MjJjYTYwNWNjMCIsImlhdCI6MTU2NzA5NTcwMX0.7MuJbY650e92M_5KO2dHmuI9s9flVjYLf2WbfSNauZI

{
    "title": "blog005",
    "author": "Erick B. Lemos",
    "url": "url",
    "likes": 123,
    "userId": "5d67e1d40bd88822ca605cc0"
}