post http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "newBlog with usera",
    "author": "Erick B. Lemos",
    "url": "url",
    "likes": 123,
    "userId": "5d67ca5c8758c356959ac191"
}